version: '3.8'
services:
  production:
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 4004
      SKIP_PREFLIGHT_CHECK: 'true'
      REACT_APP_API_MASTER: 'http://68.183.234.66:5008'
      REACT_APP_HOST_SOCKET: '68.183.234.66:5008'
    image: fe_react
    container_name: fids_fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4004:4004"
    volumes:
      - fids_fe:/var/opt/fids_fe
    networks:
      - fids_fe
volumes:
  fids_fe:
    driver: local
networks:
  fids_fe:
    driver: bridge