version: '3.8'
services:
  production:
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 8001
      REACT_APP_TITLE: 'SKRIPSI'
      SKIP_PREFLIGHT_CHECK: 'true'
      REACT_APP_API_MASTER: 'http://68.183.234.66:8000'
      REACT_APP_HOST_SOCKET: '68.183.234.66:8000'
    image: skripsi_fe
    container_name: skripsi_fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - skripsi_fe:/var/opt/skripsi_fe
    networks:
      - skripsi_fe
volumes:
  skripsi_fe:
    driver: local
networks:
  skripsi_fe:
    driver: bridge