export const GET_ANNOUNCEMENT_GLOBAL_PLAYLIST = 'ANNOUNCEMENT/GLOBAL-PLAYLIST'
export const GET_ANNOUNCEMENT_SHOW_PLAYLIST = 'ANNOUNCEMENT/SHOW-PLAYLIST'

export const MINIFY_PLAYER_ANNOUNCEMENT = 'ANNOUNCEMENT/PLAYER-MINIFY'
export const SELECT_ANNOUNCEMENT = 'ANNOUNCEMENT/SELECT'
export const CLEAR_ANNOUNCEMENT = 'ANNOUNCEMENT/CLEAR'
export const OPEN_PLAYER_ANNOUNCEMENT = 'ANNOUNCEMENT/OPEN-PLAYER'
export const CLOSE_PLAYER_ANNOUNCEMENT = 'ANNOUNCEMENT/CLOSE-PLAYER'
export const QUEUE_NEXT_MUSIC_ANNOUNCEMENT = 'ANNOUNCEMENT/QUEUE-NEXT-MUSIC'
export const QUEUE_NEXT_MUSIC_LANG_ANNOUNCEMENT = 'ANNOUNCEMENT/QUEUE-NEXT-LANG'



export const ANNOUNCEMENT_CATEGORY = `ANNOUNCEMENT/CATEGORY/LIST`
export const GET_ANNOUNCEMENT_CATEGORY_SELECTIONS_LIST = `ANNOUNCEMENT/CATEGORY/SELECTIONS-LIST`
