export const GET_MONITORING_LIST = "GET_MONITORING_LIST"
export const OK_GET_MONITORING_LIST = "OK_GET_MONITORING_LIST"
export const BAD_GET_MONITORING_LIST = "BAD_GET_MONITORING_LIST"


export const SET_HIGHLIGHT_MONITORING = "SET_HIGHLIGHT_MONITORING"
export const REMOVE_HIGHLIGHT_MONITORING = "REMOVE_HIGHLIGHT_MONITORING"