export const GET_LIST_NOTIFICATIONS = "GET_LIST_NOTIFICATIONS"
export const OK_GET_LIST_NOTIFICATIONS = 'OK_GET_LIST_NOTIFICATIONS'
export const BAD_GET_LIST_NOTIFICATIONS = 'BAD_GET_LIST_NOTIFICATIONS'

export const GET_DETAIL_NOTIFICATION = "GET_DETAIL_NOTIFICATION"
export const OK_GET_DETAIL_NOTIFICATION = 'OK_GET_DETAIL_NOTIFICATION'
export const BAD_GET_DETAIL_NOTIFICATION = 'BAD_GET_DETAIL_NOTIFICATION'