export const GET_LIST_INVITATIONS_SETTING = 'GET_LIST_INVITATIONS_SETTING'
export const OK_GET_LIST_INVITATIONS_SETTING = 'OK_GET_LIST_INVITATIONS_SETTING'
export const BAD_GET_LIST_INVITATIONS_SETTING = 'BAD_GET_LIST_INVITATIONS_SETTING'

export const CONF_INITIAL_INVITATION = 'CONF_INITIAL_INVITATION'
export const CONF_SET_INITIAL_INVITATION = 'CONF_SET_INITIAL_INVITATION'
export const CONF_OK_INITIAL_INVITATION = 'CONF_OK_INITIAL_INVITATION'
export const CONF_BAD_INITIAL_INVITATION = 'CONF_BAD_INITIAL_INVITATION'

export const EMIT_CURRENT_ACTIVE_INVITATION = 'EMIT_CURRENT_ACTIVE_INVITATION'
export const DESCRIBE_EMIT_CURRENT_INVITATION = 'DESCRIBE_EMIT_CURRENT_INVITATION'
export const SUBSCRIBE_GLOBAL_LOADING_SCREEN = 'SUBSCRIBE_GLOBAL_LOADING_SCREEN'
export const DESCRIBE_GLOBAL_LOADING_SCREEN = 'DESCRIBE_GLOBAL_LOADING_SCREEN'



export const SETTING_GENERAL_API = 'SETTING/GENERAL'
export const GET_SITE = 'SETTING/GET-SITE'