export const WEBSOCKET_CONNECT = "WEBSOCKET_CONNECT"
export const WEBSOCKET_SEND = "WEBSOCKET_SEND"
export const WEBSOCKET_MESSAGE = "WEBSOCKET_MESSAGE"
export const WEBSOCKET_DISCONNECT = "WEBSOCKET_DISCONNECT"